# Run this script with the top level directory as the working directory
stopifnot(basename(getwd()) == "sig_attribution_paper_code")
rm(list = ls())
source("analysis/code/generic_gather_and_print_stats.R")

base_sup_table = 6

generic_gather_and_print_stats("SBS", sup_table_number = base_sup_table) # tables S6, s7, s8


if (FALSE) { # Skip CPU
  sup_table_number = base_sup_table + 11 # tables s17, s18, s19
  for (mutation_type in c("SBS")) {
    gather_and_save_cpu_time(mutation_type, sup_table_number)
    sup_table_number = sup_table_number + 1
  }
}
  
# Table S20 and sup figs S7, S8, S9
# are generated by sourcing cpu_versus_num_sigs.R

# Be sure to run mean_ranks_by_tool.R and put the mean ranks 
# in each rank sup table (1 each for SBS, DBS, ID)

source("analysis/code/mean_ranks_by_tool.R")
mean_ranks_by_tool("SBS")
